### ISSUE TITLE
The (Google) search input field is not working properly

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#101]
When I'm on the main page of the site, http://uv-cdat.llnl.gov/ and I type *MV2* in the Search field at the top right, I get some results

http://uv-cdat.llnl.gov/search.html?q=MV2

But when I'm in a subsection of the site, e.g. the cdms documentation, and  I type *MV2* in the Search field at the top right, **I do not get any results**!

http://uv-cdat.llnl.gov/documentation/cdms/search.html?q=MV2

It seems that the query string is not generated properly

**Comment by chaosphere2112** [comment]
This should be fixed; I had neglected the leading "/" for the search URL, so it was trying to find the nonexistent page `/documentation/cdms/search.html` via a relative url.

**Comment by mattben** [comment]
The site is static site generated using Jekyll. The google search bar was removed due to it not working correctly, examples showing wrong info, finding outdated info from other / old sites.
