### ISSUE TITLE
"Contact Us" web page

### ISSUE THREAD

**Issue by golaz** [UV-CDAT/uvcdat-site#103]
Tried to subscribe to 'uvcdat-support' following instructions on

http://uvcdat.llnl.gov/contact.html

but it did not work. Error message from majordomo@lists.llnl.gov:

subscribe: unknown list 'uvcdat-support'.

**Comment by mattben** [comment]
Thank you for bringing this to our attention, we are transitioning to new mail list servers. We will make this update asap.

**Comment by chaosphere2112** [comment]
This has been resolved; thanks for the bug report!
