### ISSUE TITLE
Several notes about the Change Log

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#106]
@chaosphere2112 Could you remove the https://github.com/UV-CDAT/uvcdat/wiki/2.4RC3-Release-Notes page and add links from *appropriate* places of the wiki (*builld*  pages? etc...) to the relevant http://uv-cdat.llnl.gov/changelog.html on the web site

Also, I think that there maybe should be a link to the *Changelog* page from the *Installing* pull-down menu at the top (except now it's just a link and not a pull-down menu). It's not enough to have the link only below the *UV-CDAT 2.4.0 is Available* line and I had a hard time finding this information before I thought about looking there!

I understand that the idea is maybe to have change logs for release candidates on the wiki, and change logs for the stable versions on the web site, but it is too confusing to have the same similar (but not quite the same) information in 2 different places.

**Comment by chaosphere2112** [comment]
@jypeter Sure thing! Those release notes were only there so people could help me work on them while we were prepping the release. I'll take them down now. I think I'll add a "Releases" submenu on the top that will have the running changelog, and a link to an index page for release docs.

**Comment by jypeter** [comment]
Yes, a release submenu to access older versions, and have smaller web pages, would be nice!

The problem with that is that it makes it harder to search in which version a particular problem was found and/or fixed. So what would be really nice would be to add a link to a pdf file on each page, and the pdf would give the full change log
