### ISSUE TITLE
Use consistent links for Installing on the main page

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#108]
There are currently TWO different links for installing CDAT on the home page!

- A link to the web site, from the **Installing** link at the top of the page: http://uv-cdat.llnl.gov/installing.html
- A link to the wiki, from the **Install** link just below *UV-CDAT 2.4.0 is Available*: https://github.com/UV-CDAT/uvcdat/wiki/install

Please use the same link! Installation can already be confusing enough, without landing on different pages...

**Comment by aashish24** [comment]
> A link to the wiki, from the Install link just below UV-CDAT 2.4.0 is Available: https://github.com/UV-CDAT/uvcdat/wiki/install

This should be used from the web-site

**Comment by chaosphere2112** [comment]
Yeah, once I have some free time (probably tomorrow) I'll take a pass through these issues and address them.

**Comment by jypeter** [comment]
Thanks @chaosphere2112 and @aashish24 !
