### ISSUE TITLE
Going from an out-of-date "What-Is-Built?" wiki page to a sexy "What is available?" web page?

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#109]
Hi @chaosphere2112, @doutriaux1 and @aashish24 

I guess we all want more and more people to use UV-CDAT rather than installing Anaconda or Canopy and then asking how to install cdms2 inside Anaconda and Canopy. 

One of the ways to do that is **make it easy for the users to know what is available in UV-CDAT** (i.e. the standard scientific packages they need are there), right from the Home page! Right know, you have to scroll down the home page, and read the dense *The UV-CDAT Project* section, that may even be out-of-date (do we still have Paraview, Vistrails and Visit?). This could maybe be found in an *About* section at the top of the page (or something like https://www.enthought.com/products/canopy/features/)

What we have now is the *What-Is-Built* wiki page (https://github.com/UV-CDAT/uvcdat/wiki/What-Is-Built) that does not quite fit the purpose because it is:
- hard to find (from the web site home page)
- out-of-date, but Sam may already have a way to generate it automatically
- hard-to-read. It would be better to have a nice table showing a sorted list of packages, with their version number (and maybe a link to the package web site), e.g. https://www.enthought.com/products/canopy/package-index/

Such a page would also list for each package in which *build mode* it is available (https://github.com/UV-CDAT/uvcdat/wiki/Install-from-source-command-line-options). e.g., check the tickmark in the *In Canopy Express* column of the table on https://www.enthought.com/products/canopy/package-index/

**Comment by chaosphere2112** [comment]
I'll get something thrown together; shouldn't be too much work, I'll just build in lean, default, and all, grab the build_info.txt, and build a table. I'll stick a link to it from the release announcement, and we can do that going forward. Won't be automated, but isn't that much work. Maybe I'll write a script to ingest the build_info.txt files :smile:

**Comment by chaosphere2112** [comment]
I'm going to be leaving this on the What-Is-Built page, since this is (possibly) a frequently updated item. However, there's a nice table now that breaks it down, which is hopefully more useful.

**Comment by jypeter** [comment]
Great job, @chaosphere2112 !

I think this is **very useful** and there should probably be an easy way to go from the home page to this information. And now when people want to know how to install cdat into an existing distribution, you can point to this list to prove that UV-CDAT already comes with batteries included, bells and whistles, and everything the climate scientist needs

There should be a link from https://github.com/UV-CDAT/uvcdat/wiki/Install-from-source-command-line-options to this page as well

The thing that is missing, because it's not included in *build_info.txt* is the actual CDAT specific packages (cdms2 & Co, cmor2, vcs). Can you add this as well?

**Comment by jypeter** [comment]
@chaosphere2112 I again had trouble finding easily what packages (and versions) were available in UV-CDAT. Can you provide a link to https://github.com/UV-CDAT/uvcdat/wiki/What-Is-Built from the Home Page and from the ChangeLog Page (http://uv-cdat.llnl.gov/changelog.html)? Thanks!
