### ISSUE TITLE
Download link on UV-CDAT home page is wrong!

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#110]
Warning @doutriaux1 and @chaosphere2112 , the download link below *UV-CDAT 2.4.0 is Available* is completely wrong!

It points to http://sourceforge.net/projects/cdat/files/Releases/UV-CDAT/2.4.0/, where there is no 2.4.0 available! :fearful: 

If you follow the *Install* link instead, you can get to https://github.com/UV-CDAT/uvcdat/wiki/Install-on-RedHat-or-CentOS#installing-from-binary, and you eventually end up on a correct github download page

Anyway, there should probably just be a single *Download and Install* link pointing to https://github.com/UV-CDAT/uvcdat/wiki/install

**Comment by chaosphere2112** [comment]
@jypeter Whoops! That's my bad. We changed up the hosting of the tarball between when I wrote the announcement for the website and when we released. I'll fix that ASAP.
