### ISSUE TITLE
Build mode for the pre-built binaries?

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#111]
Can @aashish24 or somebody specify the build mode used for the binaries? 

On https://github.com/UV-CDAT/uvcdat/releases and similar pages

It would be nice to have this kind of information in https://github.com/UV-CDAT/uvcdat-site/issues/109 as well

**Comment by chaosphere2112** [comment]
Binaries are built using the default build mode; I updated the release notes to mention this fact.
