### ISSUE TITLE
Found some &le; and &lt; in cdms2 documentation

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#115]
@chaosphere2112 I have found some characters that were not translated correctly in the documentation

If you visit http://uv-cdat.llnl.gov/documentation/cdms/cdms_2.html#table_2.36 you can see

``` 	x &le; axis[i] &lt; y```

When what you want to see is

``` 	x <= axis[i] < y```

**Comment by chaosphere2112** [comment]
Thanks, Jean Yves! Fixed it.
