### ISSUE TITLE
Status of CDAT askbot?

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#125]
@chaosphere2112 and @doutriaux1 I have not visited the askbot for a long time and I thought I could give it a try and click on _AskBot_ in the _UV-CDAT 2.8.0 is Available_ box of http://uvcdat.llnl.gov/

Unfortunately, I get the following, after some time-out:
> Service Unavailable
> 
> The service is temporarily unavailable. Please try again later.

So, what's the status of AskBot (and related plans)?

**Comment by jypeter** [comment]
Oh well, when I clicked on http://uvcdat.askbot.com/ before, nothing happened (time out). Now I get the following
![nouvcdataskbot](https://cloud.githubusercontent.com/assets/2785573/23902930/0779d496-08c3-11e7-91cf-db4d10d88951.png)
If the Askbot Rests In Pieces, you may want to also remove the link from https://github.com/UV-CDAT/uvcdat/releases
`We also alert users to an Askbot website to help the UV-CDAT user community. This supports version 2.2 onward. See: http://uvcdat.askbot.com`

**Comment by mattben** [comment]
I've removed the link, sending email and researching what happened to the service. I'm pretty sure we're still paying for it...

**Comment by mattben** [comment]
There is no more askbot.
