### ISSUE TITLE
What is the current official name of [[UV-]CDAT]?

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#126]
@chaosphere2112 and @doutriaux1, I may have dreamed this, but I kind of remember somebody or a poster at the Washington ESGF F2F stating that the **C** in *CDAT* now stood for _Community_ or something like that. There is no mention of this either on the web site home page or on some of the wiki pages I checked.

Have I been hallucinating (and I confess I have a bad memory)?

Of course, if there is a new acronym/name, I completely understand that it can't have been updated on all the affected pages

**Comment by doutriaux1** [comment]
No official name change as of now.
