### ISSUE TITLE
What happened to the Search field?

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#129]
@chaosphere2112 @doutriaux1 @mattben Is it a bug or a feature that there is **no Search field** any more on the main web site? For an instant I feared I had just imagined that there had been a Search field before, but I have found an old issue mentioning it: https://github.com/UV-CDAT/uvcdat-site/issues/101

Considering that:
- not everything is documented, etc
- there is little traffic on the mailing list (maybe that's just because people know everything and have no questions!), **and** you can't search/read old mails of the list
- the askbot has disappeared: https://github.com/UV-CDAT/uvcdat-site/issues/125

...it would be nice to be able to easily search the web site! I understand that I can directly use Google to search the site, but it's not quite the same

**Comment by mattben** [comment]
The site is static site generated using Jekyll. The google search bar was removed due to it not working correctly, examples showing wrong info, finding outdated info from other / old sites.
