### ISSUE TITLE
Is the download link on the main web page STILL wrong?

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#133]
@chaosphere2112 and @doutriaux1 I don't know how to reopen https://github.com/UV-CDAT/uvcdat-site/issues/110

I have juste followed (again) the download link at the top of https://uv-cdat.llnl.gov/index.html and it seems you only have 2.2.0 on sourceforge
- it is misleading to have a link to something that is a bit outdated without specifying that it is outdated
- What a success! It says 20 downloads in the last week!!! But it says the download are from Lesotho and for Windows

If you change the download link there, should you also remove AskBot ( #125)?

**Comment by doutriaux1** [comment]
@mattben do you mind taking out the download link

**Comment by doutriaux1** [comment]
@mattben @chaosphere2112 did we officially drop the never used askbot?

**Comment by mattben** [comment]
Can remove them. We're still paying for it… If we don't promote it people won't use it… Either way
