### ISSUE TITLE
Slight error in the Changelog

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#141]
@chaosphere2112 when I look at the Release Notes, https://uvcdat.llnl.gov/changelog.html, I see 2 error/warning lines that probably should not be there
```
Unable to find milestone 2.10
[...]
No known issues! Unable to find milestone 2.10
```

**Comment by mattben** [comment]
site should show update a few minutes after the hour.

**Comment by jypeter** [comment]
Thanks! Is this generated by hand? I thought there was a script to pull everything needed for the Changelog

**Comment by mattben** [comment]
I believe your correct. @chaosphere2112 no longer works here, and @doutriaux1 will be in later. I've just removed the error texted and will let @doutriaux1 know about the issues.

**Comment by jypeter** [comment]
OK, I did not know! So I'll ping you for web related stuff, instead of "You or Matt" :)
