### ISSUE TITLE
Accessing and searching the archives of uvcdat-support ?

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#15]
Till there is a working askbot or some uvcdat stuff on stackoverflow as it is the case for cartopy
(http://stackoverflow.com/search?q=cartopy), is there a way to search the archives of the uvcdat-support list, or to access the archives?

I have sent a mail to majordomo@lists.llnl.gov with _index uvcdat-support_ and all I got was **No files available for uvcdat-support**

Any information about this should go to the _Mailing list_ section
http://uvcdat.llnl.gov/mailing-list.html

**Comment by mattben** [comment]
LLNL archiving of email not possible at this time.
