### ISSUE TITLE
UV-CDAT docs website: cdms/cdtime manual page problem

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat-site#46]
@mattben @chaosphere2112

It seems that the time constructor section of http://uvcdat.llnl.gov/documentation/cdms/cdms_3.html needs a tweak or two..

Migrated from https://github.com/UV-CDAT/uvcdat/issues/1136

**Comment by durack1** [comment]
@chaosphere2112 as this is closed in https://github.com/UV-CDAT/uvcdat/issues/1136 (and listed in the [current changelog](http://uvcdat-dev.llnl.gov/changelog.html)), what are the chances this could also get sorted and closed here too?

**Comment by chaosphere2112** [comment]
@durack1 I'll see what I can do– I assume the issue you're referring to is the busted table markup?

**Comment by durack1** [comment]
@chaosphere2112 yep exactly - fixed!
