### ISSUE TITLE
"Available Packages in CDAT" page is out-of-date

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#76]
When you are on the following page: http://uvcdat.llnl.gov/installing.html

And then follow the *Available Packages in CDAT* link to: https://github.com/UV-CDAT/uvcdat/wiki/What-Is-Built

... you notice that the page is more than 1 year old (*Charles edited this page on 30 Jan 2014*) and does not even mention a UV-CDAT version number

**Comment by mattben** [comment]
@doutriaux1 @aashish24 sounds like the wiki needs to be updated

**Comment by chaosphere2112** [comment]
Just updated the wiki page to include a brand-new build_info.txt, and provided platform/version info along with it.
