### ISSUE TITLE
Latest CDAT version, etc... on the main page

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#77]
Hi @chaosphere2112, I have just noticed that **the welcome page does not mention that 2.2.0 is available**: http://uvcdat.llnl.gov/index.html

As a matter of fact, **the front page should probably always list clearly the version number of the latest version** (and the availability date)! And it's probably a good place to **put a link to your nice changelog page**! http://uvcdat-dev.llnl.gov/changelog.html

The changelog page should probably also mention the version number and date, but I guess that's what you will have in the final version

Or maybe there should be a link to the following page that I have just discovered by chance and that has a link to a changelog page with a date and version number: https://github.com/UV-CDAT/uvcdat/releases

Also, I thought things were broken when I clicked on the following prominent links: *New user? Looking for help? Interested in contributing? Want to know more?* I kept on clicking and nothing happened. And then I discovered that it was because those big links were to the main page, and that the main page was already displayed. I think this is rather confusing and it may be be better to remove the links?

**Comment by mattben** [comment]
@chaosphere2112 go have a baby I'll fix

**Comment by jypeter** [comment]
Wow, congratulations @chaosphere2112 :+1:

**Comment by chaosphere2112** [comment]
Thanks @jypeter; she'll be coming along in the next 2 days (my wife is 8 days overdue currently, and they're inducing tomorrow), so I'm still working presently :smile:
