### ISSUE TITLE
The web site has no link to the askbot

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat-site#82]
You don't get any hit when you type _askbot_ in the search box of the site!
- there is currently a link to the askbot on the home page, in the _UV-CDAT 2.2.0 is Available_ box, but this is not found by the search! Is this indexed in whatever the site uses for indexing?
- there should be links to the askbot in (several) appropriate sections of the web site: 
  - **Contact** page?
  - **Contribute** at the bottom of each page?
  - **Documentation** drop-down menu?

And you can probably detail somewhere _what should be used for what_, as discussed in http://askbot-uvcdat.llnl.gov/question/5616/using-the-askbot-and-the-uvcdat-support-list/

**Comment by chaosphere2112** [comment]
@jypeter I get three results when I search:

![screen shot 2015-07-06 at 7 41 05 am](https://cloud.githubusercontent.com/assets/718512/8524849/6c68ad66-23b2-11e5-86ff-d18378d65cc9.png)

That said, I agree that there should be a link to it from somewhere in the site navigation. I'll add that.

**Comment by jypeter** [comment]
Correct, I also get the same search results, so forget about my first bullet above (... *this is not found by the search*)

I think we need links to the askbot from several locations, because we want the users to ask the relevant questions on the askbot, and we don't know what the parts of the web site the users will visit (the end users' brains work in mysterious and often  lazy ways)

**Comment by chaosphere2112** [comment]
OK; how about one link on the bottom navigation and one on the Contact page? Those seem like all of the reasonable places to stick it.

**Comment by mattben** [comment]
As of now askbot is dead again
