### ISSUE TITLE
Two tutorial links are dead

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat-site#99]
The two lower links are dead:
[Hovmöller 3D Example](http://uvcdat.llnl.gov/mov/UVCDAT_Departures_MM_annotated4.mp4)
[3D Scalar Example with calculated variable](http://uvcdat.llnl.gov/mov/UVCDAT_error_tf-ta_anno4.mp4)

**Comment by chaosphere2112** [comment]
@durack1 Fixed!

**Comment by durack1** [comment]
@chaosphere2112 great, thanks!
